name: Selenium Firefox Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Firefox (non-Snap)
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox

      - name: Install latest GeckoDriver
        run: |
          GECKO_LATEST=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep "tag_name" | cut -d '"' -f4)
          wget "https://github.com/mozilla/geckodriver/releases/download/$GECKO_LATEST/geckodriver-$GECKO_LATEST-linux64.tar.gz"
          tar -xzf geckodriver-*.tar.gz
          chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin/

      - name: Run tests with pytest and generate HTML report
        run: |
          pytest tests/ --html=report.html

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: selenium-report
          path: report.html
